#
# Jekyll build for deploying to gh-pages (called from deploy.sh)
#
version: '2'
services:

  jekyll:
    image: benizar/jekyll
    container_name: benizar_jekyll
    logging:
      driver: "none"
    ports:
      - 4000:4000
    volumes:
      - ..:/source # Your sources will be here

    command: bundle exec jekyll build
