version: '2'
services:

  jekyll:
    image: jekyll/jekyll:pages
    command: bundle exec jekyll serve --config _config.yml,_config_dev.yml --watch --incremental
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll

