#
# This one is our development environment
#
version: '2'
services:

  jekyll:
    # comment on build if want to use the dockerhub build
    build:
      context: ./workspace
      dockerfile: Dockerfile.jekyll
    image: benizar/jekyll
    container_name: benizar_jekyll
    # keep jekyll awaiting for instructions
    ports:
        - 4000:4000
    volumes:
      - .:/home
      - /usr/local/bin/

  workspace:
    # comment on build if want to use the dockerhub build
    build:
      context: ./workspace
      dockerfile: Dockerfile.tmux
    image: benizar/workspace
    container_name: benizar_workspace
    # Make docker client available within the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    volumes_from:
      - jekyll
    stdin_open: true
    tty: true

