version: '2'
services:
  #
  # [ server stack ]
  #
  # - jekyll
  #

  jekyll:
    image: benizar/jekyll:latest
    container_name: benizar_jekyll
    # Jekyll waits for tmux instructions
    entrypoint: bundle exec jekyll serve  --config _config.yml,_config_dev.yml --host 0.0.0.0 --watch --incremental
    ports:
        - 4000:4000
    volumes:
      - .:/home # Your sources will be in the container's home
