version: '2'
services:

  jekyll:

    image: benizar/jekyll
    container_name: siose_jekyll
    ports:
      - 4000:4000
    volumes:
      - .:/home # Your sources will be in the container's home

    command: jekyll serve --config _config.yml,_config_dev.yml --host 0.0.0.0 --watch --incremental
