#
# Jekyll build without --drafts for deploying on github
# This one is our development environment
#
version: '2'
services:

  worker:
    # comment on build if want to use the dockerhub build
    build:
      context: ./provision
      dockerfile: Dockerfile-worker
    image: benizar/worker
    container_name: benizar_worker
    ports:
        - 4000:4000
    volumes:
      - .:/srv/jekyll

  workspace:
    # comment on build if want to use the dockerhub build
    build:
      context: ./provision
      dockerfile: Dockerfile-workspace
    image: benizar/workspace
    container_name: benizar_workspace
    # Make docker client available within the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    volumes_from:
      - worker
    stdin_open: true
    tty: true
